<div id="payment-errors" class="validation-advice" style="display:none;"></div>

<?php $code = $this->getMethodCode() ?>
<ul id="payment_form_<?php echo $code ?>" style="display:none;"
    class="buckaroo3extended_input form-list buckaroo-method">
    <form id="cseTestForm">
        <div class="card blank">
            <div class="card_front">
                <div class="cardNumber_container">
                    <label for="cardNumber"><?php echo $this->__('Card number'); ?></label>
                    <input id="cardNumber" type="tel" name="cardNumber" placeholder="XXXX XXXX XXXX XXXX" onblur="checkCardType(this)" onkeydown="removeSpaces(this)"/>
                </div>

                <div class="expirationMonth_container">
                    <label for="expirationMonth"><?php echo $this->__('Expiration');?></label>
                    <div class="select_wrapper">
                        <select id="expirationMonth" type="text" name="expirationMonth" onblur="getEncryptedData()">
                            <option value="0"><?php echo  $this->__('Select a month'); ?></option>
                            <option value="1"><?php echo  $this->__('January');   ?></option>
                            <option value="2"><?php echo  $this->__('February');  ?></option>
                            <option value="3"><?php echo  $this->__('March');     ?></option>
                            <option value="4"><?php echo  $this->__('April');     ?></option>
                            <option value="5"><?php echo  $this->__('May');       ?></option>
                            <option value="6"><?php echo  $this->__('June');      ?></option>
                            <option value="7"><?php echo  $this->__('July');      ?></option>
                            <option value="8"><?php echo  $this->__('August');    ?></option>
                            <option value="9"><?php echo  $this->__('September'); ?></option>
                            <option value="10"><?php echo $this->__('October');   ?></option>
                            <option value="11"><?php echo $this->__('November');  ?></option>
                            <option value="12"><?php echo $this->__('December');  ?></option>
                        </select>
                    </div>

                    <input id="expirationYear" type="text" name="expirationYear" onblur="getEncryptedData()" placeholder="<?php echo $this->__('Year: XXXX');?>"/>
                </div>

                <div class="cardHolderName_container">
                    <label for="cardHolderName"><?php echo $this->__('Name cardholder');?></label>
                    <input id="cardHolderName" type="text" name="cardHolderName" onblur="getEncryptedData()" placeholder="<?php echo $this->__('Name');?>"/>
                </div>
            </div>

            <div class="card_back">
                <div class="magnet_stripe"></div>
                <div class="card_security">
                    <label for="cvc"><?php echo $this->__('Security code');?></label>
                    <input id="cvc" type="text" name="cvc" onblur="getEncryptedData()" placeholder="XXX"/>
                </div>
                <div class="card_kind">
                    <img class="creditcard-logo" alt="Credit Card type" height="25" src="<?php echo $this->getSkinUrl('images/tig_buckaroo3extended/creditcard_types/creditcard_blank.png');?>" />
                </div>
                <input type="hidden" name="buckaroo3extended_creditcard_encryptedCardData" id="buckaroo3extended_creditcard_encryptedCardData"/>
                <input type="hidden" name="buckaroo3extended_creditcard_method" id="buckaroo3extended_creditcard_method"/>
            </div>
        </div>
    </form>
</ul>

<script>
    jQuery_1123('#cardNumber').on("keydown", function(){
       if(jQuery_1123('#cardNumber').val().length <= 4){
           jQuery_1123('.creditcard-logo').attr("src", "<?php echo $this->getSkinUrl('images/tig_buckaroo3extended/creditcard_types/creditcard_blank.png');?>");
        }
    });
</script>