<div id="payment-errors" class="validation-advice" style="display:none;"></div>

<?php $code = $this->getMethodCode() ?>
<ul id="payment_form_<?php echo $code ?>" style="display:none;"
    class="buckaroo3extended_input form-list buckaroo-method">
    <form id="cseTestForm">
        <div class="card <?php echo $this->designValue() ?>">
            <div class="card_front">

                <div class="cardType_container">
                    <label for="cardType"><?php echo $this->__('Card type'); ?></label>
                    <div class="select_wrapper">
                        <select id="cardType" class="required-entry" name="cardType" onblur="getEncryptedData()">
                            <option value="Card type"><?php echo  $this->__('Card type');   ?></option>
                        </select>
                    </div>
                </div>

                <div class="cardNumber_container">
                    <label for="cardNumber"><?php echo $this->__('Card number'); ?></label>
                    <input id="cardNumber" class="required-entry" type="tel" name="cardNumber" onblur="processCardNumber(this)" onkeydown="removeSpaces(this)"/>
                </div>

                <div class="expiration_container">
                    <label for="expirationMonth"><?php echo $this->__('Expiration');?></label>
                    <div class="select_wrapper">
                        <select id="expirationMonth" class="required-entry" name="expirationMonth" onblur="getEncryptedData()">
                            <option value="0"><?php echo  $this->__('Month'); ?></option>
                            <option value="1"><?php echo  $this->__('01 - January');   ?></option>
                            <option value="2"><?php echo  $this->__('02 - February');  ?></option>
                            <option value="3"><?php echo  $this->__('03 - March');     ?></option>
                            <option value="4"><?php echo  $this->__('04 - April');     ?></option>
                            <option value="5"><?php echo  $this->__('05 - May');       ?></option>
                            <option value="6"><?php echo  $this->__('06 - June');      ?></option>
                            <option value="7"><?php echo  $this->__('07 - July');      ?></option>
                            <option value="8"><?php echo  $this->__('08 - August');    ?></option>
                            <option value="9"><?php echo  $this->__('09 - September'); ?></option>
                            <option value="10"><?php echo $this->__('10 - October');   ?></option>
                            <option value="11"><?php echo $this->__('11 - November');  ?></option>
                            <option value="12"><?php echo $this->__('12 - December');  ?></option>
                        </select>
                    </div>

                    <div class="select_wrapper" >
                        <select id="expirationYear" class="required-entry" name="expirationYear" onblur="getEncryptedData()">
                            <option value="0"><?php echo  $this->__('Year'); ?></option>
                            <option value="1"><?php echo  $this->__('2019');   ?></option>
                            <option value="2"><?php echo  $this->__('2020');   ?></option>
                            <option value="3"><?php echo  $this->__('2021');   ?></option>
                        </select>
                    </div>
                </div>

                <div class="cardHolderName_container">
                    <label for="cardHolderName"><?php echo $this->__('Name cardholder');?></label>
                    <input id="cardHolderName" type="text" class="required-entry" name="cardHolderName" onblur="getEncryptedData()" />
                </div>
            </div>

            <div class="card_back">
                <div class="magnet_stripe"></div>
                <div class="card_security">
                    <label for="cvc"><?php echo $this->__('Security code');?></label>
                    <div class="field">
                        <input id="cvc" type="text" class="required-entry" name="cvc" onblur="getEncryptedData()" />
                    </div>
                    <div class="info">
                        <svg xmlns="http://www.w3.org/2000/svg" width="510" height="510" viewBox="0 0 510 510"><path d="M229.5 382.5h51v-153h-51V382.5zM255 0C114.8 0 0 114.8 0 255s114.8 255 255 255 255-114.7 255-255S395.3 0 255 0zM255 459c-112.2 0-204-91.8-204-204S142.8 51 255 51s204 91.8 204 204S367.2 459 255 459zM229.5 178.5h51v-51h-51V178.5z"/></svg>
                        <div class="popup">
                            <?php echo $this->__('Or "CVV" or "CVC". <br/><br/> A 3-digit code located to the right of signature strip on the back of your card, separate from the card number.'); ?>
                        </div>
                    </div>
                </div>
                <div class="card_kind">
                    <img class="creditcard-logo" alt="Credit Card type" height="35" src="<?php echo $this->getSkinUrl('images/tig_buckaroo3extended/creditcard_types/creditcard_blank.png');?>" />
                </div>
                <input type="hidden" name="buckaroo3extended_creditcard_encryptedCardData" id="buckaroo3extended_creditcard_encryptedCardData"/>
                <input type="hidden" name="buckaroo3extended_creditcard_method" id="buckaroo3extended_creditcard_method"/>
            </div>
        </div>
    </form>
</ul>

<script>
    jQuery_1123('#cardNumber').on("keydown", function(){
       if(jQuery_1123('#cardNumber').val().length <= 4){
           jQuery_1123('.creditcard-logo').attr("src", "<?php echo $this->getSkinUrl('images/tig_buckaroo3extended/creditcard_types/creditcard_blank.png');?>");
        }
    });
</script>